### ISSUE TITLE
[BUG] Fix issues with waiting for a response

### ISSUE THREAD

**Issue by artificialbutter** [artificialbutter/SpongeChat#12]
- Typing will stop even though the bot is still thinking
- Queue of messages can build up, maybe add a limit?

**Comment by artificialbutter** [comment]
yeah idc it's fine i'm sure

**Comment by Butterroach** [comment]
> Typing will stop even though the bot is still thinking

you can fix this by just spamming the typing api every 7 secs or smth i think
