### ISSUE TITLE
[enhancement] Let Spongechat know the current date and time

### ISSUE THREAD

**Issue by Butterroach** [artificialbutter/SpongeChat#29]
# Suggestion

Add the current date and time (in UTC)  to the start of prompts sent to Spongechat.

# Why

So Spongechat can know the difference in time between messages. (and it'd be cool)

# Character.AI already knows the date

Not the time, and it doesn't know the date for every message.

# Template string because I'm too lazy for this shit

Everything in the squiggly bracket stuff should be replaced (idk what they're called, leave the normal brackets alone)

```
[{date in UTC} {time in UTC, 12 hour mode} {am/pm} UTC+0]
```

# Funny image

![DRV mic-50AD9FDF-DD34-D293-31B9-ABB48A67FFE1-1024x768.jpg](https://github.com/artificialbutter/SpongeChat/assets/111113093/ce975980-4c6b-4173-8c91-96ce6b97f792)

# ...

![Screenshot_20240411_190154.png](https://github.com/artificialbutter/SpongeChat/assets/111113093/d62a4f3c-be0e-42ff-8a8d-31021610219f)

# Feel free to close this as not planned

**Comment by Butterroach** [comment]
I am good at writing great and helpful GitHub issues

**Comment by artificialbutter** [comment]
:trollface:

**Comment by Butterroach** [comment]
Sure I'll do it if you give me access to the entire repo and allow me to put porn in the readme
