### ISSUE TITLE
[BUG] res.text will be undefined when response is large/takes too long to generate

### ISSUE THREAD

**Issue by artificialbutter** [artificialbutter/SpongeChat#8]

**Comment by artificialbutter** [comment]
hey butterroach :trollface:

**Comment by Butterroach** [comment]
> hey butterroach :trollface:

why did you decide to use this specific issue

**Comment by artificialbutter** [comment]
> > hey butterroach :trollface:
> 
> 
> 
> why did you decide to use this specific issue

first one that I saw

**Comment by artificialbutter** [comment]
THIS IS WHY YOU DONT RUN INTERNAL APIS THROUGH CLOUDFLARE!!!!!
